### ISSUE TITLE
KNN returns points number less than specified

### ISSUE THREAD

**Issue by mkabischev** [hongshibao/go-kdtree#2]
Hi, we've tried to use your library but faced the problem.

I've added one more point to your test case and it returns the wrong response:
```go
func TestKNN(t *testing.T) {
	points := []Point{
		NewEuclideanPoint(0.0, 0.0, 0.0),
		NewEuclideanPoint(0.0, 0.0, 1.0),
		NewEuclideanPoint(0.0, 1.0, 0.0),
		NewEuclideanPoint(1.0, 0.0, 0.0),
		NewEuclideanPoint(0.0, 0.0, 0.0),
		NewEuclideanPoint(0.0, 0.0, 0.1),
		NewEuclideanPoint(1.0, 1.0, 1.0),
		NewEuclideanPoint(0.1, 0.1, 0.1), // aditional point
	}

	tree := NewKDTree(points)

	ans := tree.KNN(NewEuclideanPoint(0.0, 0.0, 0.0), 7)
	if len(ans) != 7 {
		t.Errorf("expected 7 points, actual: %v", len(ans))
	}
}
```

This test returns 
```github.com/hongshibao/go-kdtree/kdtree_test.go:116: expected 7 points, actual: 5```

If I add one more point a get error:
```github.com/hongshibao/go-kdtree/kdtree_test.go:117: expected 7 points, actual: 6```

**Comment by hongshibao** [comment]
Thanks @mkabischev for pointing this issue out. I have fixed it and submitted to the master branch. I also added your test case and my one more test case. Feel free to contact me if there are still other issues.
